name: scenv
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy=1.15.3
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - anndata=0.11.4
  - scanpy=1.10.2
  - pytorch=1.3
  - polars
  - statsmodels
  - pymer4
  - pip:
      - scvi-tools==1.3
      - liana==0.1.7
      - harmonypy
      - symphonypy

