name: scenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10

  # Core numerical stack (conda only)
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels

  # Single-cell / graph
  - scanpy=1.11.4
  - anndata=0.11.4
  - igraph
  - leidenalg

  # Jupyter
  - jupyterlab
  - notebook

  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - git+https://github.com/Novartis/scAR.git
      - scvi-tools[extra]
      - liana==0.1.7
      - polars
      - pymer4
      - mygene
