name: scenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - igraph
  - leidenalg
  - jupyterlab
  - pip
  
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - git+https://github.com/Novartis/scAR.git
      - scvi-tools[extra]
      - scanpy==1.11.4
      - anndata==0.11.4
      - scipy==1.15.3
      - liana==0.1.7
      - harmonypy
      - symphonypy
      - notebook
      - polars
      - statsmodels
      - pymer4
      - mygene
